name: Baby Finn
favicon: null
layout_spectrum: 0.8494273491669446
typography_spectrum: 0.7769908797927201
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9474176971707493
  lightness: 0.11080943094566464
  saturation: 0.08298326143994927
  rhythmicContrast: 0.2750196252018213
purpose: []
